version: '3.8'
services:
  nostalgia-sync:
    build: .
    container_name: nostalgia-sync
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on: []
    # Add volumes or database links here if needed
